# acr-nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      imagePullSecrets:
        - name: acr-auth   # Reference the secret here, outside of containers
      containers:
      - name: nginx
        image: AKSCR1mmoore.azurecr.io/samples/nginx:latest
        ports:
        - containerPort: 80
