# deployment.yaml for ADO pipeline (rough draft / needs testing)

trigger:
- main

variables:
  azureSubscription: 'adoServiceConnection'
  acrName: 'AKSCR1mmoore.azurecr.io'
  imageName: 'samples/nginx'
  kubernetesCluster: 'your-aks-cluster-name'
  resourceGroup: 'your-resource-group-name'
  deploymentFile: 'acr-nginx.yaml'
  dockerImage: 'nginx:latest'

stages:
- stage: BuildAndDeploy
  displayName: 'Build and Deploy'
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and deploy to AKS'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI - Setup and Login to ACR/AKS'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(resourceGroup) --name $(kubernetesCluster)
          az acr login --name $(acrName)

    - task: AzureCLI@2
      displayName: 'Pull, push and deploy image to AKS'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Pull the latest Nginx image, tag, and push to ACR
          docker pull $(dockerImage)
          docker tag $(dockerImage) $(acrName)/$(imageName):latest
          docker push $(acrName)/$(imageName):latest

          # Deploy to AKS and monitor deployment
          kubectl apply -f $(deploymentFile)
          kubectl rollout status deployment/nginx0-deployment